Innodev 5
mrisrsvpu/INNODEV-5 pull request #3
Opened 2019-03-12 10:12 UTC by Alexandr18

2019-03-12 10:19 UTC, MikhailChe requested changes
Нам точно здесь нужны yarn.lock и log файлы с ошиками? Репозиторий не для этого, нужно почистить.

2019-03-12 10:19 UTC, MikhailChe commented on app.js
> +        i <= 7
Это нужно сократить. Например сделать формулу маппинга одного числа к другому или сделать словарик и проходиться по нему циклом.

2019-03-12 10:19 UTC, MikhailChe commented on app.js
> +      // console.log(output_day_date[day_num].data[day]); // Дата               //
Никакого дебажного кода в продакшн среде быть не должно.

2019-03-12 10:19 UTC, MikhailChe commented on app.js
> +module.exports = app;
В конце файлов с исходными кодами всегда нужно оставлять пустую строчку

2019-03-12 10:19 UTC, MikhailChe commented on config.js
> +  };
Пустая строчка

2019-03-12 10:31 UTC, MikhailChe requested changes

2019-03-12 10:31 UTC, MikhailChe commented on .gitignore
> +yarn.lock
Новая строка

2019-03-12 10:31 UTC, MikhailChe commented on app.js
> +app.get("/grup/:id", function(req, res) {
Вообще, неплохо было бы переименовать grup  в group , чтобы было грамотно. Так сделать везде, в том числе в документации (README)

2019-03-12 11:09 UTC, JleMyP commented on app.js
> +      // console.log(output_day_date[day_num].data[day]); // Дата               //
а если завернуть в `if DEBUG:...`?

2019-03-12 14:33 UTC, MikhailChe commented on app.js
> +      // console.log(output_day_date[day_num].data[day]); // Дата               //
Надо посмотреть, есть ли у console.log параметр для логгирования только в случае дебага. 
if DEBUG будет смотреться отвратительно, особенно если таких дебагов будет в каждой функции в случайных местах по несколько штук. Нужна какая-то обёртка, которая бы делала функционал if DEBUG но с точки зрения пользовательского кода выглядела как обычный однострочный вызов.

2019-03-12 14:36 UTC, MikhailChe requested changes

2019-03-12 14:36 UTC, MikhailChe commented on README.md
> +# GET: /grup/:id
group

2019-03-12 14:36 UTC, MikhailChe commented on README.md
>  # localhost:3000/grup/2806
group

2019-03-12 14:36 UTC, MikhailChe commented on app.js
> +var results_name_grup = [];
results_name_group

2019-03-12 14:36 UTC, MikhailChe commented on app.js
> +  results_name_grup = [];
results_name_group

2019-03-12 14:36 UTC, MikhailChe commented on app.js
> +    results_name_grup = $(".rasp_header").text(); //ок
results_name_group

2019-03-12 14:36 UTC, MikhailChe commented on app.js
> +        name_of_grup: results_name_grup, //Номер группы
name_of_group: results_name_group

2019-03-12 15:19 UTC, MikhailChe submitted a review, later dismissed

2019-03-12 15:30 UTC, JleMyP submitted a review, later dismissed

2019-03-12 15:30 UTC, JleMyP commented on app.js
> +var g;
что такое `g`?

2019-03-13 12:40 UTC, MikhailChe approved these changes

2019-03-13 12:40 UTC, merged