Docker
mrisrsvpu/INNODEV-5 pull request #4
Opened 2019-03-13 14:18 UTC by JleMyP

2019-03-13 14:44 UTC, MikhailChe requested changes
Давай dockerfile с большой буквы будем писать.

2019-03-13 14:44 UTC, MikhailChe commented on README.md
> +запуск образа - `docker run --rm -ti mris/parser`
Давай сюда тоже имя поставим

2019-03-13 14:44 UTC, MikhailChe commented on .dockerignore
> +.git*
Мне кажется, что не стоит здесь так много добавлять в dockerignore.

2019-03-13 14:44 UTC, MikhailChe commented on dockerfile
> +COPY package.json /home/parser/
А почему /home/parser ? Обычно же кладут в /app

2019-03-13 14:44 UTC, MikhailChe commented on docker-compose.yml
> +      - "443:443"
Зачем нам https? Для внутренних сервисов хватит обычного http, тем более сертификатов у нас нет.

2019-03-13 14:45 UTC, JleMyP commented on README.md
> +запуск образа - `docker run --rm -ti mris/parser`
имя файла? `-f Dockerfile`?

2019-03-14 05:36 UTC, MikhailChe requested changes
Пожалуйста, нужно начинать сообщения коммитов с названия тикета, чтобы коммит привязывался к тикету.

2019-03-14 05:36 UTC, MikhailChe commented on README.md
> -сборка образа - `docker build -t mris/parser .`
Это было не обязательно. Речь шла о переименовании самого файла

2019-03-14 06:05 UTC, MikhailChe approved these changes

2019-03-14 06:46 UTC, merged